[package]
name = "sprattus-derive"
version = "0.1.0"
authors = ["Martijn <martijn@tweedegolf.nl>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.5", features = ["extra-traits"]}
quote =  { version = "1.0.2" }
proc-macro2 = "1.0.2"