[package]
name = "profugus"
version = "0.1.0"
authors = ["Martijn <martijn@tweedegolf.nl>"]
edition = "2018"

[dependencies]
tokio-postgres = "0.4.0-rc.3"
tokio = "^0.1.0"
futures = "0.1.28"
parking_lot = "0.9.0"